export const Users = [
    {
        id: 1,
        profilePicture: "/assets/person/image (1).jpg",
        username: "Rajesh Kumar",
    },
    {
        id: 2,
        profilePicture: "/assets/person/image (2).jpg",
        username: "Anjali Sharma",
    },
    {
        id: 3,
        profilePicture: "/assets/person/image (3).jpg",
        username: "Vikram Patel",
    },
    {
        id: 4,
        profilePicture: "/assets/person/image (4).jpg",
        username: "Priya Desai",
    },
    {
        id: 5,
        profilePicture: "/assets/person/image (5).jpg",
        username: "Ramesh Yadav",
    },
    {
        id: 6,
        profilePicture: "/assets/person/image (6).jpg",
        username: "Neha Reddy",
    },
    {
        id: 7,
        profilePicture: "/assets/person/image (7).jpg",
        username: "Arjun Mehta",
    },
    {
        id: 8,
        profilePicture: "/assets/person/image (8).jpg",
        username: "Sakshi Verma",
    },
    {
        id: 9,
        profilePicture: "/assets/person/image (9).jpg",
        username: "Manoj Singh",
    },
    {
        id: 10,
        profilePicture: "/assets/person/image (10).jpg",
        username: "Kavya Nair",
    },
];

export const Posts = [
    {
        id: 1,
        desc: "Sowing seeds of hope for a better harvest.",
        photo: "/assets/agro-loop/v1.mp4",
        date: "5 mins ago",
        userId: 1,
        like: 32,
        comment: 9,
        dislike : 1,
    },
    {
        id: 2,
        desc: "Healthy soil, healthy crops, healthy lives.",
        photo: "/assets/agro-loop/v2.mp4",
        date: "15 mins ago",
        userId: 2,
        like: 25,
        comment: 4,
        dislike : 0,
    },
    {
        id: 3,
        desc: "A good crop is a farmer's true reward.",
        photo: "/assets/agro-loop/v3.mp4",
        date: "20 mins ago",
        userId: 3,
        like: 45,
        comment: 12,
        dislike : 5,
    },
    {
        id: 4,
        desc: "The joy of seeing a field turn green.",
        photo: "/assets/agro-loop/v4.mp4",
        date: "30 mins ago",
        userId: 4,
        like: 18,
        comment: 3,
        dislike : 1,
    },
    {
        id: 5,
        desc: "Every drop of water counts in farming.",
        photo: "/assets/agro-loop/v5.mp4",
        date: "45 mins ago",
        userId: 5,
        like: 11,
        comment: 2,
        dislike : 0,
    },
    {
        id: 6,
        desc: "Nature is the best teacher for a farmer.",
        photo: "/assets/agro-loop/v6.mp4",
        date: "1 hour ago",
        userId: 6,
        like: 39,
        comment: 7,
        dislike : 3,
    },
    {
        id: 7,
        desc: "The harder you work, the better the yield.",
        photo: "/assets/agro-loop/v7.mp4",
        date: "2 hours ago",
        userId: 7,
        like: 52,
        comment: 15,
        dislike : 1,
    },
    {
        id: 8,
        desc: "Crop rotation is the secret to sustainable farming.",
        photo: "/assets/agro-loop/v8.mp4",
        date: "3 hours ago",
        userId: 8,
        like: 28,
        comment: 6,
        dislike : 2,
    },
    {
        id: 9,
        desc: "A farm is more than land and crops, it's our future.",
        photo: "/assets/agro-loop/v9.mp4",
        date: "4 hours ago",
        userId: 9,
        like: 21,
        comment: 5,
        dislike : 7,
    },
    {
        id: 10,
        desc: "Harvest time is the fruit of hard work and patience.",
        photo: "/assets/agro-loop/v10.mp4",
        date: "5 hours ago",
        userId: 10,
        like: 37,
        comment: 10,
        dislike : 3,
    },
];


export const CuPosts = [
    {
        id: 1,
        desc: "Love for the land, care for the crops, and hope for a bountiful harvest.",
        photo: "/assets/post/image (1).jpg",
        date: "5 mins ago",
        userId: 1,
        like: 32,
        comment: 9,
    },
    {
        id: 2,
        photo: "/assets/post/image (2).jpg",
        date: "15 mins ago",
        userId: 2,
        like: 25,
        comment: 4,
    },
    {
        id: 3,
        desc: "Every moment in the field is a fresh beginning for growth and prosperity.",
        photo: "/assets/post/image (3).jpg",
        date: "20 mins ago",
        userId: 3,
        like: 45,
        comment: 12,
    },
    {
        id: 4,
        desc: "Dream big, work hard, and see your fields bloom with abundant crops.",
        photo: "/assets/post/image (4).jpg",
        date: "30 mins ago",
        userId: 4,
        like: 18,
        comment: 3,
    },
    {
        id: 5,
        photo: "/assets/post/image (5).jpg",
        date: "45 mins ago",
        userId: 5,
        like: 11,
        comment: 2,
    },
    {
        id: 6,
        desc: "Happiness is homemade, just like the fruits of our hard work in the fields.",
        photo: "/assets/post/image (6).jpg",
        date: "1 hour ago",
        userId: 6,
        like: 39,
        comment: 7,
    },
    {
        id: 7,
        desc: "Be yourself; every farmer has a unique way of making the land flourish.",
        photo: "/assets/post/image (12).jpg",
        date: "2 hours ago",
        userId: 7,
        like: 52,
        comment: 15,
    },
    {
        id: 8,
        photo: "/assets/post/image (8).jpg",
        date: "3 hours ago",
        userId: 8,
        like: 28,
        comment: 6,
    },
    {
        id: 9,
        desc: "Let your dreams be your wings, just like the seeds we plant for a better future.",
        photo: "/assets/post/image (9).jpg",
        date: "4 hours ago",
        userId: 9,
        like: 21,
        comment: 5,
    },
    {
        id: 10,
        desc: "Stay positive, work hard, and watch your crops grow and thrive with patience.",
        photo: "/assets/post/image (10).jpg",
        date: "5 hours ago",
        userId: 10,
        like: 37,
        comment: 10,
    },
];
